export const GET_TOP_MOVIES_BY_DATE = 'GET_TOP_MOVIES_BY_DATE';
export const GET_TOP_MOVIES_BY_DATE_REQUEST = 'GET_TOP_MOVIES_BY_DATE_REQUEST';
export const GET_TOP_MOVIES_BY_DATE_SUCCESS = 'GET_TOP_MOVIES_BY_DATE_SUCCESS';
export const GET_TOP_MOVIES_BY_DATE_FAIL = 'GET_TOP_MOVIES_BY_DATE_FAIL';


export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';
export const GET_MOVIE_BY_ID_REQUEST = 'GET_MOVIE_BY_ID_REQUEST';
export const GET_MOVIE_BY_ID_SUCCESS = 'GET_MOVIE_BY_ID_SUCCESS';
export const GET_MOVIE_BY_ID_FAIL = 'GET_MOVIE_BY_ID_FAIL';